### ISSUE TITLE
Make program page template dynamic

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#37]
Currently it has simple html in it; we need to add the content.

**Comment by mattstratton** [comment]
Looking at the existing datafile for events, there is an element that lists all the speakers.

I believe we could add some optional parameters to them, basically "date", "start time", and "end time" which would put them into the program.

The challenge is going to be adding things to the program that are not talks; perhaps the right move is something like this:

```yaml

program:
  - title: "Welcome and Opening"
    type: custom
    date: 2016-01-01
    start_time: "08:00"
    end_time: "08:15"
  - id: "nicole-forsgren"
    type: talk
    date: 2016-01-01
    start_time: "08:15"
    end_time: "09:15"

```

**Comment by mattstratton** [comment]
This depends on #4, because it affects how we get at speaker data.

**Comment by mattstratton** [comment]
The other option is to have to create a file for every portion of the schedule, so you would have `content/events/YYYY-CITY/program/welcome-and-breakfast-1.md` with all the frontmatter, etc, and create them over and over. This could end up with a bunch of junk.

There's an upside to it - if you do this with Open Spaces as well, you could easily dump the content of each open space into the `content/events/YYYY-CITY/program/day-one-open-space-1.md` file and do a quick merge.

None of this handles multi-track well; that's something that if an event is multi-track they'll probably just have to do a custom page.

**Comment by mattstratton** [comment]
OK, I was playing around in a branch, and sorta got this working with the YAML.

The additional YAML looks like this:

```yaml
program:
  - title: "Registration, Breakfast, and Sponsor Booths Open"
    type: custom
    date: 2016-01-01
    start_time: "08:00"
    end_time: "09:00"
  - title: "Opening Welcome"
    type: custom
    date: 2016-01-01
    start_time: "09:15"
    end_time: "09:00"
  - title: "rainbow-dash"
    type: talk
    date: 2016-01-01
    start_time: "09:15"
    end_time: "09:45"
  - title: "Sponsors"
    type: custom
    date: 2016-01-01
    start_time: "09:45"
    end_time: "09:55"
  - title: "apple-jack"
    type: talk
    date: 2016-01-01
    start_time: "09:55"
    end_time: "10:25"
  - title: "Break"
    type: custom
    date: 2016-01-01
    start_time: "10:25"
    end_time: "10:40"
  - title: "fluttershy"
    type: talk
    date: 2016-01-01
    start_time: "10:40"
    end_time: "11:10"
  - title: "Sponsors"
    type: custom
    date: 2016-01-01
    start_time: "11:10"
    end_time: "11:20"
  - title: "twilight-sparkle"
    type: talk
    date: 2016-01-01
    start_time: "11:20"
    end_time: "11:50"
  - title: "Lunch (catered)"
    type: custom
    date: 2016-01-01
    start_time: "11:50"
    end_time: "13:00"
```

Was it a pain to do? Sorta. Was it better than copy-pasting a lot of `<div>` statements? Probably. I think it's better than the "make a bunch of markdown files for each portion of the event including breaks" though.
